### ISSUE TITLE
pianoroll

### ISSUE THREAD

**Issue by vivienseguy** [Yikai-Liao/symusic#50]
Hello,

import symusic
sysmusic.Score(midi_file_path).pianoroll(modes=["frame"], pitch_range=(0, 128),  encode_velocity=False)

gives me the error:
TypeError: pianoroll(): incompatible function arguments. The following argument types are supported:
    1. pianoroll(self, modes: collections.abc.Sequence[str], pitch_range: tuple[int, int] = (0, -128), encode_velocity: bool = False) -> numpy.ndarray[dtype=uint8]
Invoked with types: symusic.core.ScoreTick, kwargs = { modes: list, pitch_range: tuple, encode_velocity: bool }

**Expected behavior**

symusic 0.5.1 running on python 3.11 on MacOS (M2 chip)

Same with 
sysmusic.Score(midi_file_path).tracks[0].pianoroll(modes=["frame"], pitch_range=(0, 128),  encode_velocity=False)

**Comment by lzqlzzq** [comment]
Thanks for your feedback! It' s a pity our test had not covered `pianoroll` yet.

Unfortunately, this problem is related to `C++ binding`. But you may still use this feature with `symusic==0.4.8`.

Another friendly suggestion is to always use `.sample(tpq)` before `.pianoroll(...)` to avoid potential memory explosion.

**Comment by vivienseguy** [comment]
Thank you very much, this worked. Thank you also for the suggestion, I was doing that already :)

**Comment by lzqlzzq** [comment]
Fixed in `v0.5.2`.
