### ISSUE TITLE
Stereo can't be passed as a keyword argument to render method

### ISSUE THREAD

**Issue by realfolkcode** [Yikai-Liao/symusic#53]
Symusic version: 0.5.3
(tested with `example_mahler.mid`)

In the synthesis section of the docs, following the midi rendering example leads to the TypeError:

```
audio = synth.render(s, stereo=True) # stereo is True by default, which means you will get a stereo wave

TypeError: render(): incompatible function arguments. The following argument types are supported:
    1. render(self, arg0: symusic.core.ScoreTick, arg1: bool, /) -> numpy.ndarray[dtype=float32, shape=(*, *), order='F']
    2. render(self, arg0: symusic.core.ScoreQuarter, arg1: bool, /) -> numpy.ndarray[dtype=float32, shape=(*, *), order='F']
    3. render(self, arg0: symusic.core.ScoreSecond, arg1: bool, /) -> numpy.ndarray[dtype=float32, shape=(*, *), order='F']

Invoked with types: symusic.core.Synthesizer, symusic.core.ScoreTick, kwargs = { stereo: bool }
```
However, passing stereo as a non-keyword argument seems to work fine:
`audio = synth.render(s, True)`

**Comment by Yikai-Liao** [comment]
Thanks for your report, and I have fixed this in main branch.

And I further checked other bindings. Despite those methods for list (like insert), which does not support key word argument in python, I should have added all the argument names.

We apologize for the inconvenience caused by refactoring.
